### ISSUE TITLE
[실습1] 사용성 테스트 : 평가요소

### ISSUE THREAD

**Issue by s-eunbi-kim** [s-eunbi-kim/UT_20240708#1]
사용성을 개선하고 싶은 App을 선정하고, 앱의 사용성을 평가해보자.
* App 선정
* Usability Factor / 사용성 10가지 원칙 등을 참고하여 “평가 요소” 1~3개 선정
* 해당 평가 요소를 기반으로 앱 평가

**Comment by dlekdms2** [comment]
* 선정한 App : 휴대폰 연락처 App, 연락 기록 창에서 휴대폰 번호 복사
해당 기능을 사용하기 위해서는 아래와 같은 순서가 요구된다
수신/발신된 기록 터치 -> 메뉴 아이콘 선택 -> 상단의 번호 꾹 누르기 -> 번호 복사하기 터치
이를 아래와 같이 변경
수신/발신된 기록을 꾹 누르기 -> 번호 복사하기 터치

* 평가 요소 1 : 2) Match Between System and the RealWorld - 디바이스에 띄워지는 텍스트 정보들을 꾹 누르면 해당 부분이 드래그되며 복사하기 옵션이 함께 뜬다. 이와 같이 기록된 번호를 꾹 누르는 action 하나만으로 복사를 가능하게 한다.
* 평가 요소 2 : 7) Flexibility and Efficiency of Use - 사용자의 Mental Model을 고려하여 별도의 터치 없이 길게 누름으로 번호 복사를 가능하게 한다.

* 해당 요소를 기반으로 앱 평가 : 사용자의 Mental Model을 반영하고 기존보다 줄어든 Action으로 사용자에게 더 편리함을 줄 수 있다.

**Comment by saway126** [comment]
선정한 App : 네이버 지도
평가 요소 : 7(flexibility of use):움직일 때 마다 내 위치가 변경 될 때마다 목적지를 다시 입력해주어야 했는데 내 위치에 따라 자동으로 출발지를 바꿔주면 좋을 것 같다.
8(minimalist Design):  지도 UI가 개인적으로 작다고 느껴지고 위치가 부정확하거나 세세하게 나오지 않는 내용들이 있어서 불편함을 느끼는데 이러한 디자인들을 다시 업데이트 해주면 좋을것 같다.
9(Help Users Recognize): 걸어서 목적지에 갈 때 경로 이탈 시 경고 메시지나 알람이 울리게

**Comment by KSM0429** [comment]
- 선정한 App : 윈도우 11버전의 마우스 우클릭 옵션
 - 평가 요소 : 4번 Consistency and Standards
 - 개요 : 기존의 윈도우 11 이전 버전의 마우스 우클릭 옵션과 윈도우 11의 우클릭 옵션의 인터페이스가 다름
 - 개선안 : 윈도우 11의 마우스 우클릭 옵션 인터페이스를 이전 버전과 동일하게 설정 가능하게 함

**Comment by Liorunner01** [comment]
선정한 App :melon 에서 좋아하기 한 컨탠츠 멜론 앱 클릭시 초기화면에서 바로가기 생성

평가요소  : 
 
ⓐ현실 일치 = 많은 유저가 자신이 듣고싶은 음악들을 플레이리스트로 반복 재생한다.
ⓐ유저 자율 제어 = 초기화면에서 제어할수 있게 함으로서  usability 향상 
ⓒ유연성과 효율성 = 시간을 절약함으로서 서버로 가는 트레픽 줄임

**Comment by shin02160** [comment]
선정한 App : Weverse앱의 Store
퍙가요소 : 5. Error Prevention
- 개수제한이 있는 상품의 경우, 상품 정보에서 개수 초과하여 Cart 담기 불가하지만 유효한 개수를 반복하여 담은 경우, 가능하며 결제 시, 오류 발생됨
=> 결제 이전에 Cart에서 구매 가능한 수량이 초과 되었음을 알려주거나 자동 수정된다면 사용성 개선될 것으로 판단됨.

평가요소 : 7. Match between system and the real world
- 상품 검색 기능 없음. (상품 검색 기능이 없어 카테고리 선택 후 스크롤하여 해당 상품을 수동으로 검색하여야함.)
=> 일반적으로 쇼핑 앱에 검색 기능이 기본적으로 존재하지만, 해당 기능이 없어 상품 검색이 어려움. 해당 기능 추가 필요할 것으로판단됨.

**Comment by bok-rye** [comment]
깃허브 처음 사용해봐요..

**Comment by bok-rye** [comment]
사용성을 개선하고 싶은 App을 선정하고, 앱의 사용성을 평가해보자.

App 선정 : Notes
Usability Factor / 사용성 10가지 원칙 등을 참고하여 “평가 요소” 1~3개 선정
2. 현실세계와 부합하도록 설계: 아이콘모양이 익숙
3. 사용자제어와 통제권: 목록에서 메모 삭제가능
5. 오류 방지: 입력시 추천어 제공

**Comment by hebyun-unity** [comment]
선정한App:  SKT의 공인전자문서함
  - 시스템상태 알림없음, 버튼을 클릭한 후 한참을 동일한 화면에서 기다려야 함
  - 심미성 전혀 없음

**Comment by Helluoo** [comment]
선정한 APP : Gaming Hub
Visibility of system status -> 특정기능화면에서 이 화면이 어떤 화면이고 현재 어떤 상황인지 바로 인지된다.
Recognition rather than recall -> 무엇을 하면 어떤 기능을 사용할 수 있는지 바로바로 인지된다.
Aesthetic and minimalist design -> 인터페이스가 아주 간결하며 쓸떼 없는 버튼 또는 글씨가 없다.

**Comment by doorbee21** [comment]
선정한 APP :  지하철 관련 앱.

원칙 4: 일관성 및 표준성
평가: 지하철 앱에서 실시간 상황이 제대로 반영되지 않음, 이는 사용자에게 혼란을 줄 수 있음. 예를 들어, 역에 도착하기도 전에 이미 열차가 출발했다고 표시되면 사용자는 앱의 정보에 신뢰를 잃게 됨. 일관성 있는 정보를 제공하는 것이 중요합니다. 실시간 정보가 정확하게 반영되어야 사용자가 올바른 결정을 내릴 수 있습니다.

원칙 9: 오류 인식, 진단 및 복구

평가: 예정 시간과 현재 상황이 맞지 않는 경우가 잦다면, 앱은 이러한 오류를 인식하고 사용자에게 알리며, 상황을 진단하여 해결책을 제시해야 함. 예를 들어, "현재 실시간 정보 업데이트에 문제가 있습니다. 예상 도착 시간을 참조하세요."와 같은 메시지를 제공하여 사용자가 혼란스러워 하지 않도록 도와야 할 것임.

원칙 10: 도움말 및 문서화

평가: 앱에서 실시간 상황이 반영되지 않거나 예정 시간과 현재 상황이 맞지 않는 경우, 사용자는 이러한 문제를 해결할 수 있는 도움말이나 문서가 필요함. 앱 내에 문제 해결을 위한 FAQ나 고객 지원 연락처를 쉽게 찾을 수 있어야 합니다. 또한, 사용자가 실시간 정보를 확인하는 방법과 예기치 않은 상황에 대처하는 방법에 대한 가이드를 제공해야 할 것입니다.

**Comment by LEEJUNHYUKK** [comment]
선정한 App : 카카오 뱅크
평가 요소 : 1. Consistency and Standards.
2. Recognition Rather than Recall.
3. Flexibility and Efficiency of Use 

1번 평가 요소 App평가 : 일관성 있는 구조(상품 설명 및 계좌 시스템) 및 정보(금융서비스)를 사용자에게 제공하는 이 App은 1번 평가 요소 원칙을 잘 수행하여 사용자가 이 App을 쉽게 이해하고 배울 수 있다.

2번 평가 요소 App평가 : 계좌 사용 시 자주 사용하는 계좌를 쉽게 기억해내고, 그들의 계좌 그룹또한 편리하게 표시하는 이 App은 2번 평가 요소 원칙을 잘 수행했으며 사용자의 적은 노력에도 App을 유용하게 사용할 수 있다.

3번 평가 요소 App평가 : 은행의 전문 서비스를 그대로 옮겨 닮은 이 App은 전문성이 뛰어나 일반 사용자들도 쉽게 이용가능하고 App의 신속, 자동적인 수행 능력은 사용자가 시스템을 유연하고 효율적으로 사용할 수 있도록 한다.

**Comment by jenniferLee7** [comment]
따로 사용하는 앱에 없으므로 강사님이 제시하신 아이폰 모든 읽음 처리 기능에 대한 10가지 중 부족한 것으로 생각되는 요소를 적어보았습니다. 
1) 다른 폰에 있는 기능인데 없으므로 2번원칙 일반적인 현실과 부합하지 않는 것 같습니다.
2) 사용자가 효율적으로 사용할 수 없기 때문에 7번 원칙에 부합되지 않는 것 같습니다.
3) 사용자에게 다양한 선택권이 주어지지 않으므로 3번 원칙에 부합되지 않는 것 같습니다. 
이상입니다.

**Comment by Choi-Bowon** [comment]
선정한 App : 고용노동부 HRD-Net (전자 출결 기능)
평가 요소: 
1. 효율성
    - 선택할 수 있는 출결 방식이 세가지 있지만, 실제론 비콘 방식만 사용함.
    - 신호 방식을 선택하면 훈련 과정이 존재하지 않는다는 에러 발생
    - 메인 페이지에서 주로 사용하는 한 가지 방식만 제공한다면 사용성이 향상될 것으로 예상됨.
2. 회상보다 인지
    - 실행 화면의 큐알 방식 아이콘은 직관적으로 와닿지 않는다고 느낌. 
    - 비콘이라는 용어도 블루투스로 변경한다면 사용자가 더 이해하기 쉬울 것 같다.
2. 일관성과 표준
    - 사전 화면과 메인 화면에서 출결 방식 선택 아이콘과 용어의 통일성이 유지되지 않음.
    - 아이콘과 용어를 통일하여 일관성을 맞춘다면 사용성이 향상될 것 같다.

**Comment by zmgpgp8** [comment]
선정한 App : instagram
평가 요소 : match between system and the real world
                   10 u
흔들어서 문제현상 알림 알림 이슈
조금만 움직여도 흔들어서 문제발생 팝업뜸. 인스타그램을 보는중 뛰거나 할수없다보니
 설정가능하게 유저가 직접 변경할 수 있게 하는것이 좋음.

**Comment by sunghyunnnnn** [comment]
선정한App: 인스타그램 탐색바
• 2 consistency 계정마다 탐색바 항목이 달라 일관성이 부족하다
• 4 learnability 처음 인스타그램을 접한 유저들에게 탐색바의 각 항목을 쉽게 이해 및 사용의 안내 제공 및 툴팁 필요
• 6 flexibility 사용자가 원하는 필터링 할 수 있는 기능 부족, 자주 사용하는 기능을 자유롭게 탐색 바에 추가 및 제거 기능, 커스터 마이즈 옵션 제공 필요(개인화 된 사용자 걍험 지원)

**Comment by zmgpgp8** [comment]
선정한 App : instagram
평가 요소 : match between system and the real world

흔들어서 문제현상 알림 알림 이슈
조금만 움직여도 흔들어서 문제발생 팝업뜸. 인스타그램을 보는중 뛰거나 할수없다보니
설정가능하게 유저가 직접 변경할 수 있게 하는것이 좋을 것 같음.

**Comment by jjy1006** [comment]
App 선정: 아이폰 기본 카메라
Usability Factor / 사용성 10가지 원칙 등을 참고하여 “평가 요소” 1~3개 선정
* 10.Help and Documentation
해당 평가 요소를 기반으로 앱 평가
아이폰 카메라의 모든 100% 기능을 활용할 수 있는 방법에 대한 기본 튜토리얼이나 설명서가 없음

**Comment by suboil** [comment]
App 선정 : 카카오톡
                  송금 시 친구추가가 되어 있어야만 송금 가능

2. Match Between System & Real World
    리얼 월드에서는 친구가 아니어도 송금이 가능하다.

7. Flexibility And Efficiency of Use
    보다 유연하고 효울적으로 사용할 수 있다.

**Comment by ATH-MSR7** [comment]
app : 플레이키보드

1. 실용적이지 못한 일본어 입력 (② Match between system and the real world)
2. 키보드 상단의 툴바를 제거할 수 없어서 사용 중 화면을 많이 가림 (⑧ Aesthetic and Minimalist Design)
